app/routes.php
<?php
/* Rotas da aplicação
* 
*/

Route::get('/', ['as'=>'home', 'uses'=>'SiteController@home']);

# User Register
Route::get('cadastro',['before'=>'already.logged','as'=>'user.register','uses'=>'AuthController@register']);
Route::post('cadastro',['as'=>'user.post.register','uses'=>'AuthController@postRegister']);
Route::get('cadastro/confirmado',['as'=>'user.register.return','uses'=>'AuthController@registerReturn']);
Route::get('cadastro/confirmacao/{activationCode}', ['as'=>'user.register.activation', 'uses'=>'AuthController@activation']);
Route::get('login',['as'=>'user.login','uses'=>'AuthController@login']);
Route::post('login',['as'=>'user.post.login','uses'=>'AuthController@postLogin']);
Route::get('logout',['as'=>'user.logout','uses'=>'AuthController@logout']);

# Passwords
Route::get('recuperar/senha', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('resetar/senha/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);

# Admin
Route::get('admin', ['before'=>'already.logged.admin', 'as'=>'admin.login', 'uses'=>'AuthController@adminLogin']);
Route::post('admin', ['as'=>'admin.post.login', 'uses'=>'AuthController@postAdminLogin']);

Route::group(['prefix'=>'admin', 'before'=>'auth|admin'], function(){
	# Dashoboard
	Route::get('dashboard', ['as'=>'admin.dashboard', 'uses'=>'AdminController@dashboard']);

	# Posts / Conteúdos
	Route::resource('conteudos', 'PostsController');

	# Categorias
	Route::resource('categorias', 'CategoriesController');

	# Logout
	Route::get('logout', ['as'=>'admin.logout', 'uses'=>'AuthController@adminLogout']);
});

app/views/admin/partials/menu.blade.php
{{-- MENU --}}
<div class="col-md-3">
   <div class="menu-lateral">
      <ul>
         <li>
            <a href="{{ route('admin.conteudos.index') }}">Conteúdos</a>
            <ul>
               <li>
                  <a href="{{ route('admin.categorias.index') }}">Categorias</a>
               </li>
               <li>
                  <a href="#">Vídeos</a>
               </li>
            </ul>
         </li>
         <li>
            <a href="#">Franquia</a>
         </li>
         <li>
            <a href="#">Corretora</a>
         </li>
         <li>
            <a href="#">FAQs</a>
         </li>
         <li>
            <a href="#">Externos</a>
         </li>
         <li>
            <a href="#">Relatórios</a>
         </li>
      </ul>
   </div>
</div>

app/views/admin/partials/top.blade.php
<div class="header-admin">
   <div class="row">
      <div class="col-md-6">
         <img class="logo" src="{{ asset('img/logo-rsa-dark.png') }}">
      </div>
      <div class="col-md-6">
         <select class="actions_admin_select select-menu pull-right">
            <option disabled selected>{{ Sentry::getUser()->name }}</option>
            <option value="{{-- route('user.edit') --}}">Meus dados</option>
            <option value="{{ route('admin.logout') }}">Sair</option>
         </select>
      </div>
   </div>
</div>